import type { Metadata } from 'next';
import './globals.css';
import { comfortaa } from './constants/font';

export const metadata: Metadata = {
  title: 'Bao & Chau Wedding',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} antialiased`}>{children}</body>
    </html>
  );
}
